db:
  image: postgres:9.6
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
    - ./pgdata:/var/lib/postgresql/data/pgdata

api:
  build: ./api
  # command: tail -f /dev/null
  command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  volumes:
    - ./api:/usr/src/api
  ports:
    - "9080:8000"
  links:
    - db
