# Generated by Django 2.2.6 on 2019-10-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_post_code', models.CharField(max_length=50)),
                ('delivery_status', models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='created', max_length=10)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='orders.OrderModel')),
                ('pizza_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.PizzaVariantModel')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
