# Generated by Django 2.2.6 on 2019-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
