# Generated by Django 2.2.6 on 2019-10-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
        migrations.CreateModel(
            name='PizzaVariantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('personal', 'Personal'), ('large', 'Large'), ('familiar', 'Familiar')], max_length=10)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.PizzaModel')),
            ],
            options={
                'db_table': 'pizza_variant',
                'unique_together': {('pizza', 'size')},
            },
        ),
    ]
